---
# tasks file for vm-role-nfs-server
# https://github.com/geerlingguy/ansible-role-nfs/tree/master

- name: Ensure NFS utilities are installed.
  ansible.builtin.apt:
    name:
      - nfs-common
      - nfs-kernel-server
    state: present

- name: Ensure directories to export exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  with_items: "{{ nfs_exports | map('split') | map('first') | unique }}"

- name: Copy exports file.
  ansible.builtin.template:
    src: 'exports.j2'
    dest: /etc/exports
    owner: root
    group: root
    mode: '0644'
  notify: reload nfs

- name: Ensure nfs is running.
  ansible.builtin.service:
    name: nfs-kernel-server
    state: started
    enabled: true
  when: nfs_exports | length
